[2025-09-20T11:28:09.617+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_to_staging.load_sales_stg scheduled__2025-09-19T00:00:00+00:00 [queued]>
[2025-09-20T11:28:09.629+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_to_staging.load_sales_stg scheduled__2025-09-19T00:00:00+00:00 [queued]>
[2025-09-20T11:28:09.632+0200] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2025-09-20T11:28:09.653+0200] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): load_sales_stg> on 2025-09-19 00:00:00+00:00
[2025-09-20T11:28:09.659+0200] {standard_task_runner.py:57} INFO - Started process 4073 to run task
[2025-09-20T11:28:09.665+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'raw_to_staging', 'load_sales_stg', 'scheduled__2025-09-19T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/dag_raw_to_staging.py', '--cfg-path', '/tmp/tmp1_j1npkw']
[2025-09-20T11:28:09.675+0200] {standard_task_runner.py:85} INFO - Job 33: Subtask load_sales_stg
[2025-09-20T11:28:09.825+0200] {task_command.py:410} INFO - Running <TaskInstance: raw_to_staging.load_sales_stg scheduled__2025-09-19T00:00:00+00:00 [running]> on host 1102361e702e
[2025-09-20T11:28:09.984+0200] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='raw_to_staging' AIRFLOW_CTX_TASK_ID='load_sales_stg' AIRFLOW_CTX_EXECUTION_DATE='2025-09-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-19T00:00:00+00:00'
[2025-09-20T11:28:09.984+0200] {sql.py:265} INFO - Executing: 
            INSERT INTO staging.sales_stg (sale_date, store_id, product_id, qty, revenue)
            SELECT date::date, store_id, product_id, qty, revenue
            FROM raw.sales_generated;
        
[2025-09-20T11:28:10.023+0200] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-09-20T11:28:10.131+0200] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-09-20T11:28:10.139+0200] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 145, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"

[2025-09-20T11:28:10.166+0200] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=raw_to_staging, task_id=load_sales_stg, execution_date=20250919T000000, start_date=20250920T092809, end_date=20250920T092810
[2025-09-20T11:28:10.185+0200] {standard_task_runner.py:109} ERROR - Failed to execute job 33 for task load_sales_stg (connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"
; 4073)
[2025-09-20T11:28:10.215+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-09-20T11:28:10.264+0200] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
